# Generated by Django 5.2.7 on 2026-04-18 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
