# Generated by Django 5.2.8 on 2026-05-12 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_status_idempotencykey'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='hours_per_day',
            field=models.IntegerField(blank=True, help_text='Hours per day for hourly/monthly modes', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='monthly_duration_months',
            field=models.IntegerField(blank=True, help_text='Duration in months (1-6 months)', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='working_days',
            field=models.JSONField(blank=True, default=list, help_text="List of day names e.g. ['Mon','Tue','Wed','Thu','Fri','Sat']"),
        ),
    ]
