# Generated by Django 5.2.8 on 2026-05-12 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_hours_per_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_type',
            field=models.CharField(choices=[('daily', 'Daily'), ('monthly', 'Monthly'), ('hourly', 'Hourly')], default='daily', max_length=20),
        ),
    ]
