# Generated by Django 5.2.7 on 2026-05-29 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_remove_booking_booking_type_bookingchangerequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_type',
            field=models.CharField(choices=[('daily', 'Daily'), ('monthly', 'Monthly'), ('hourly', 'Hourly'), ('tool', 'Tool')], default='daily', max_length=20),
        ),
    ]
