# Generated by Django 5.2.7 on 2026-05-04 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='skill',
            field=models.CharField(choices=[('mason', 'Mason'), ('carpenter', 'Carpenter'), ('electrician', 'Electrician'), ('plumber', 'Plumber'), ('welder', 'Welder'), ('painter', 'Painter'), ('tile_worker', 'Tile Worker'), ('concrete_worker', 'Concrete Worker'), ('roofer', 'Roofer'), ('house_cleaner', 'House Cleaner'), ('cook', 'Cook'), ('babysitter', 'Babysitter'), ('caretaker', 'Caretaker'), ('gardener', 'Gardener'), ('pest_control', 'Pest Control Worker'), ('loader', 'Loader / Unloader'), ('mover', 'Mover'), ('delivery', 'Delivery Worker'), ('driver', 'Driver'), ('ac_technician', 'AC Technician'), ('fridge_technician', 'Refrigerator Repair Technician'), ('washing_technician', 'Washing Machine Technician'), ('mobile_technician', 'Mobile Repair Technician'), ('computer_technician', 'Computer Technician'), ('farm_worker', 'Farm Worker'), ('harvester', 'Harvester'), ('irrigation', 'Irrigation Worker'), ('dairy_worker', 'Dairy Worker'), ('factory_worker', 'Factory Worker'), ('machine_operator', 'Machine Operator'), ('packaging_worker', 'Packaging Worker'), ('warehouse_worker', 'Warehouse Worker'), ('event_setup', 'Event Setup Worker'), ('decorator', 'Decorator'), ('sound_light', 'Sound/Light Technician'), ('security_guard', 'Security Guard')], db_index=True, max_length=50),
        ),
    ]
