# Generated by Django 5.2.8 on 2026-05-12 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_alter_worker_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='bio',
            field=models.TextField(blank=True, help_text='Brief biography or description of the worker', max_length=500),
        ),
        migrations.AddField(
            model_name='worker',
            name='is_id_verified',
            field=models.BooleanField(default=False, help_text="Whether the worker's ID has been verified"),
        ),
        migrations.AddField(
            model_name='worker',
            name='languages',
            field=models.JSONField(blank=True, default=list, help_text="List of languages spoken, e.g. ['Kannada', 'English']"),
        ),
        migrations.AddField(
            model_name='worker',
            name='response_time_minutes',
            field=models.IntegerField(default=15, help_text='Average minutes to accept a booking'),
        ),
        migrations.AddField(
            model_name='worker',
            name='service_areas',
            field=models.JSONField(blank=True, default=list, help_text='List of service area location names'),
        ),
        migrations.AddField(
            model_name='worker',
            name='specializations',
            field=models.TextField(blank=True, help_text="Specializations or expertise areas, e.g. 'Home wiring, Inverter installation'"),
        ),
        migrations.AddField(
            model_name='worker',
            name='working_hours_end',
            field=models.TimeField(blank=True, help_text='End time of working hours (HH:MM format)', null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='working_hours_start',
            field=models.TimeField(blank=True, help_text='Start time of working hours (HH:MM format)', null=True),
        ),
    ]
